# Generated by Django 3.2 on 2021-12-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
