# Generated by Django 3.2 on 2021-12-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_task', '0002_projectmanager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='name',
        ),
    ]
