# Generated by Django 3.2.8 on 2021-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True),
        ),
    ]
